version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  pre_build:
    commands:
      - node --version
      - npm --version
      - npx --version
      - npm install -g npx
      - npx --version
      - echo Build started on `date`
  build:
    commands:
      - npx nuxi generate
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  base-directory: ./.output/public
  files:
    - '**/*'

cache:
  paths:
    - './node_modules/**/*'